package com.sesoc.test.vo;

/**
 * ITR_COMPANY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CompanyVO {

	/** COMPANY 회사명. */
	private String coName;

	/** COMPANY 아이디. */
	private String companyId;

	/** COMPANY 비밀번호. */
	private String companyPwd;

	/** COMPANY 전화번호. */
	private String coTel;

	/** COMPANY 담당자이름. */
	private String coManagerName;

	/** COMPANY 담당자의 소속 부서. */
	private String coManagerDept;

	/** CO_MANAGER_EMAIL. */
	private String coManagerEmail;

	/** COMPANY 승인여부. */
	private int coAuthority;

	public CompanyVO() {}

	public CompanyVO(String coName, String companyId, String companyPwd, String coTel, String coManagerName,
			String coManagerDept, String coManagerEmail, int coAuthority) {
		super();
		this.coName = coName;
		this.companyId = companyId;
		this.companyPwd = companyPwd;
		this.coTel = coTel;
		this.coManagerName = coManagerName;
		this.coManagerDept = coManagerDept;
		this.coManagerEmail = coManagerEmail;
		this.coAuthority = coAuthority;
	}

	public String getCoName() {
		return coName;
	}

	public void setCoName(String coName) {
		this.coName = coName;
	}

	public String getCompanyId() {
		return companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyPwd() {
		return companyPwd;
	}

	public void setCompanyPwd(String companyPwd) {
		this.companyPwd = companyPwd;
	}

	public String getCoTel() {
		return coTel;
	}

	public void setCoTel(String coTel) {
		this.coTel = coTel;
	}

	public String getCoManagerName() {
		return coManagerName;
	}

	public void setCoManagerName(String coManagerName) {
		this.coManagerName = coManagerName;
	}

	public String getCoManagerDept() {
		return coManagerDept;
	}

	public void setCoManagerDept(String coManagerDept) {
		this.coManagerDept = coManagerDept;
	}

	public String getCoManagerEmail() {
		return coManagerEmail;
	}

	public void setCoManagerEmail(String coManagerEmail) {
		this.coManagerEmail = coManagerEmail;
	}

	public int getCoAuthority() {
		return coAuthority;
	}

	public void setCoAuthority(int coAuthority) {
		this.coAuthority = coAuthority;
	}

	@Override
	public String toString() {
		return "CompanyVO [coName=" + coName + ", companyId=" + companyId + ", companyPwd=" + companyPwd + ", coTel="
				+ coTel + ", coManagerName=" + coManagerName + ", coManagerDept=" + coManagerDept + ", coManagerEmail="
				+ coManagerEmail + ", coAuthority=" + coAuthority + "]";
	}
	
	
	
	
	
	
	
}
	
	
	