package com.sesoc.test.vo;

/**
 * ITR_GALLERY 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GalleryVO {

	/** GALLERY 번호. */
	private int galleryNum;

	/** ITR_USER 아이디. */
	private String id;

	/** IMG 서버에 저장되는 파일명. */
	private String imgUuid1;
	
	private String imgUuid2;

	private String imgUuid3;

	/** GALLERY 제목. */
	private String title;

	/** GALLERY 내용. */
	private String content;

	/** GALLERY 작성 날짜. */
	private String inputdate;

	/** GALLERY 조회수. */
	private int hit;

	@Override
	public String toString() {
		return "GalleryVO [galleryNum=" + galleryNum + ", id=" + id + ", imgUuid1=" + imgUuid1 + ", imgUuid2="
				+ imgUuid2 + ", imgUuid3=" + imgUuid3 + ", title=" + title + ", content=" + content + ", inputdate="
				+ inputdate + ", hit=" + hit + "]";
	}

	public GalleryVO() {
		super();
	}

	public GalleryVO(int galleryNum, String id, String imgUuid1, String imgUuid2, String imgUuid3, String title,
			String content, String inputdate, int hit) {
		super();
		this.galleryNum = galleryNum;
		this.id = id;
		this.imgUuid1 = imgUuid1;
		this.imgUuid2 = imgUuid2;
		this.imgUuid3 = imgUuid3;
		this.title = title;
		this.content = content;
		this.inputdate = inputdate;
		this.hit = hit;
	}

	public int getGalleryNum() {
		return galleryNum;
	}

	public void setGalleryNum(int galleryNum) {
		this.galleryNum = galleryNum;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getImgUuid1() {
		return imgUuid1;
	}

	public void setImgUuid1(String imgUuid1) {
		this.imgUuid1 = imgUuid1;
	}

	public String getImgUuid2() {
		return imgUuid2;
	}

	public void setImgUuid2(String imgUuid2) {
		this.imgUuid2 = imgUuid2;
	}

	public String getImgUuid3() {
		return imgUuid3;
	}

	public void setImgUuid3(String imgUuid3) {
		this.imgUuid3 = imgUuid3;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getInputdate() {
		return inputdate;
	}

	public void setInputdate(String inputdate) {
		this.inputdate = inputdate;
	}

	public int getHit() {
		return hit;
	}

	public void setHit(int hit) {
		this.hit = hit;
	}

	
}